import satori from 'satori';
import { Resvg } from '@resvg/resvg-js';
import { supabase } from '@/lib/supabase';

// Load a font (We need a font buffer). 
// For serverless/edge, we usually fetch it or bundle it. 
// For simplicity, let's try to fetch a Google Font or use a local dummy if offline.
// *** IMPORTANT ***: In a real Next.js app, we should load fonts from the filesystem or fetch.
// We'll use a fetch helper here.

async function loadFont() {
    // Fetch 'Noto Sans Thai' for Thai support
    const response = await fetch('https://github.com/google/fonts/raw/main/ofl/notosansthai/NotoSansThai-Regular.ttf');
    return await response.arrayBuffer();
}

export async function generateInfographic(type: 'daily_top5' | 'trending_now', data: any[]) {
    try {
        console.log(`Generating infographic for ${type}...`);
        const fontData = await loadFont();

        const template = (
            <div
                style={{
                    display: 'flex',
                    flexDirection: 'column',
                    width: '100%',
                    height: '100%',
                    backgroundColor: '#1a1a1a', // Dark theme
                    color: 'white',
                    padding: '40px',
                    fontFamily: '"Noto Sans Thai"',
                }}
            >
                {/* Header */}
                <div style={{ display: 'flex', alignItems: 'center', marginBottom: '30px' }}>
                    <div style={{ fontSize: '48px', fontWeight: 'bold', color: '#FFD700', marginRight: '20px' }}>
                        {type === 'daily_top5' ? '🏆 5 ข่าวเด่นประจําวัน' : '🔥 Trending Now'}
                    </div>
                </div>

                {/* List */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                    {data.slice(0, 5).map((item, index) => (
                        <div key={index} style={{ display: 'flex', alignItems: 'flex-start', backgroundColor: '#2d2d2d', padding: '20px', borderRadius: '12px' }}>
                            <div style={{
                                fontSize: '40px',
                                fontWeight: 'bold',
                                color: index === 0 ? '#ff4d4d' : '#888',
                                width: '60px',
                                marginRight: '20px'
                            }}>
                                {index + 1}.
                            </div>
                            <div style={{ display: 'flex', flexDirection: 'column' }}>
                                <div style={{ fontSize: '28px', fontWeight: 'bold', marginBottom: '8px', overflow: 'hidden', whiteSpace: 'nowrap', textOverflow: 'ellipsis', maxWidth: '900px' }}>
                                    {item.title}
                                </div>
                                <div style={{ fontSize: '20px', color: '#ccc' }}>
                                    {item.insight ? item.insight.substring(0, 100) + '...' : 'สรุปข่าวเด่นประจำวัน'}
                                </div>
                            </div>
                        </div>
                    ))}
                </div>

                {/* Footer */}
                <div style={{ position: 'absolute', bottom: '20px', right: '40px', fontSize: '16px', color: '#666' }}>
                    Generated by Auto News Ranking
                </div>
            </div>
        );

        // 1. Generate SVG with Satori
        const svg = await satori(template, {
            width: 1200,
            height: 1200, // Instagram Square size
            fonts: [
                {
                    name: 'Noto Sans Thai',
                    data: fontData,
                    weight: 400,
                    style: 'normal',
                },
            ],
        });

        // 2. Convert SVG to PNG with Resvg
        const resvg = new Resvg(svg, {
            fitTo: { mode: 'width', value: 1200 },
        });
        const pngData = resvg.render();
        const pngBuffer = pngData.asPng();

        // 3. Upload to Supabase Storage
        const fileName = `${type}_${Date.now()}.png`;
        const { data: uploadData, error: uploadError } = await supabase
            .storage
            .from('post-images') // Make sure this bucket exists!
            .upload(fileName, pngBuffer, {
                contentType: 'image/png',
                upsert: false
            });

        if (uploadError) throw uploadError;

        // 4. Get Public URL
        const { data: { publicUrl } } = supabase
            .storage
            .from('post-images')
            .getPublicUrl(fileName);

        return publicUrl;

    } catch (error) {
        console.error("Infographic Generation Failed:", error);
        return null; // Return null on failure so we don't break the whole flow
    }
}
